apiVersion: v2
name: cray-sts
version: 0.8.0
description: Kubernetes resources for cray-sts
keywords:
  - cray-sts
home: https://github.com/Cray-HPE/cray-sts
dependencies:
  - name: cray-service
    version: ~10.0.5
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
  - name: kimjensen-hpe
  - name: bklei
  - name: brantk-hpe
appVersion: 0.7.0
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Updated images to CSM patched versions
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-sts/issues/12
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-sts/pull/11
  artifacthub.io/images: |
    - name: cray-sts
      image: artifactory.algol60.net/csm-docker/stable/cray-sts:0.7.0
  artifacthub.io/license: MIT
