#
# MIT License
#
# (C) Copyright 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-sts
version: 0.8.2
description: Kubernetes resources for cray-sts
keywords:
  - cray-sts
home: https://github.com/Cray-HPE/cray-sts
dependencies:
  - name: cray-service
    version: ~10.0.6
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
  - name: kimjensen-hpe
  - name: bklei
  - name: brantk-hpe
appVersion: 0.8.2
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Updated images to CSM patched versions
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-sts/issues/12
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-sts/pull/11
  artifacthub.io/images: |
    - name: cray-sts
      image: artifactory.algol60.net/csm-docker/stable/cray-sts:0.8.2
  artifacthub.io/license: MIT
